service: example
provider:
  name: aws
  runtime: python2.7

functions:
  hello:
    handler: handler.hello
    events:

#Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
Outputs:
     NewOutput:
       Description: "Description for the output"
       Value: "Some output value"
